= Makerfabs DW3000 UWB ESPHome component
:reproducible:

== Abstract

This repository contains an https://esphome.io/[ESPHome] component `uwb` that allows using https://www.makerfabs.com/esp32-uwb-dw3000.html?search=DW3000[Makerfabs ESP32 UWB DW3000] devices and setup for real-time precise localization of a device.

For **practical use**, a minimum of four DW3000 devices are needed:

* 1x DW3000 as `tag`: **Moving** device to be located,
* 3x DW3000 as `anchor`: **Fixed** device with known location.

Using UWB distance/range measurements between the tag with (at least) 3 anchors, the location of the tag can be calculated.
The tag reports its calculated location to a https://www.home-assistant.io/[Home Assistant] instance.

include::doc/quick_start.adoc[]

== How localisation works

== Full documentation

== Antenna delay calibration

== License

The author's sources are provided under `Apache-2.0` license.

This repository contains a copy of https://github.com/Makerfabs/Makerfabs-ESP32-UWB-DW3000[Makerfabs-ESP32-UWB-DW3000] folder `Dw3000` licensed under `Apache-2.0`.

== Disclaimer

The original author of this repository has no business relationship with Makerfabs and does not intend to promote the use of Makerfabs ESP32 UWB DW3000 devices.
