substitutions:
  # substitution to declare ${dw3000_sources} relative to the .yaml
  # You will have to change to match with your directory structure.
  dw3000_sources: ../../components/uwb/dw3000/src
  # tag declarations
  tag_name: "tag"
  tag_device_id: "0x02"
  # all anchor declarations
  anchor1_name: "A1"
  anchor1_device_id: "0xA1"
  anchor1_latitude: "48.1234567"
  anchor1_longitude: "11.1234567"
  anchor3_name: "A3"
  anchor3_device_id: "0xA3"
  anchor3_latitude:  "48.1234568"
  anchor3_longitude: "11.1234568"

esp32:
  board: esp32dev
  framework:
    type: arduino # required by dw3000 sources

esphome:
  # copies dw3000_sources to .esphome/build/${NODE}/src/ folder
  includes:
    - ${dw3000_sources}/dw3000.h
    - ${dw3000_sources}/dw3000_config_options.cpp
    - ${dw3000_sources}/dw3000_config_options.h
    - ${dw3000_sources}/dw3000_device_api.cpp
    - ${dw3000_sources}/dw3000_device_api.h
    - ${dw3000_sources}/dw3000_mac_802_15_4.cpp
    - ${dw3000_sources}/dw3000_mac_802_15_4.h
    - ${dw3000_sources}/dw3000_mutex.cpp
    - ${dw3000_sources}/dw3000_port.cpp
    - ${dw3000_sources}/dw3000_port.h
    - ${dw3000_sources}/dw3000_regs.h
    - ${dw3000_sources}/dw3000_shared_defines.h
    - ${dw3000_sources}/dw3000_shared_functions.cpp
    - ${dw3000_sources}/dw3000_shared_functions.h
    - ${dw3000_sources}/dw3000_types.h
    - ${dw3000_sources}/dw3000_uart.cpp
    - ${dw3000_sources}/dw3000_uart.h
    - ${dw3000_sources}/dw3000_vals.h
    - ${dw3000_sources}/dw3000_version.h

external_components:
  - source: github://realzoulou/esphome-uwb-dw3000@master
    components: [ uwb ]

# Allow Over-The-Air updates
ota:
- platform: esphome

# Enable logging
logger:

# Enable Home Assistant API
api:
# and ESPHome dashboard
dashboard_import:
  package_import_url: github://esphome/example-configs/esphome-web/esp32.yaml@main
  import_full_config: false
# visit device directly
web_server:
  local: true
  include_internal: true
  version: 3

button:
- platform: restart
  name: Restart
- platform: safe_mode
  name: Safe Mode Boot
