packages:
  esphome: !include .uwb-common.yaml

substitutions:
  name: min-anchor-1
  friendly_name: UWB-Anchor-1

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: '1.0'

wifi:
  domain: !secret wifi_domain
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password

#####################################################
uwb:
  role: anchor
  device_id: ${anchor1_device_id} # unique ID of this device
