#
# Example minimal anchor ESPHome configuration
#
# run in root folder of this repository with:
#  esphome run sample_configuration/minimal/minimal_anchor.yaml
#
packages:
  esphome: !include .uwb-common.yaml

substitutions:
  name: min-anchor-1
  friendly_name: UWB-Anchor-1

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: '1.0'

wifi:
  networks:
  - ssid: YOUR_SSID
    password: YOUR_WIFI_PASSWORD

#####################################################
uwb:
  role: anchor
  device_id: ${anchor1_device_id} # unique ID of this device
